// Posibles estados de nuestro flujo
export const STATES = {
  IDLE: "IDLE",
  SENDING: {
    ACCEPT_TERMS_AND_CONDITIONS: "SENDING_ACCEPT_TERMS_AND_CONDITIONS",
    BIRTHDATE: "SENDING_BIRTHDATE",
    CONFIRMATION: "SENDING_CONFIRMATION",
    ID_NUMBER: "SENDING_ID_NUMBER",
    ID_TYPE: "SENDING_ID_TYPE",
    NOTHING_TO_RENEW_MESSAGE: "SENDING_NOTHING_TO_RENEW_MESSAGE",
    SELECTED_EPS_SERVICE: "SENDING_SELECTED_EPS_SERVICE",
    SELECTED_PROCEDURE_OPTION: "SENDING_SELECTED_PROCEDURE_OPTION",
    SELECTED_PROCS_AND_MEDS_OPTION: "SENDING_SELECTED_PROCS_AND_MEDS_OPTION",
    SUCCESS_MESSAGE_ALERT: "SENDING_SUCCESS_MESSAGE_ALERT",
  },
  WAKING_UP_EPS_BOT: "WAKING_UP_EPS_BOT",
  WAITING: {
    FOR_ACTIVE_PRESCRIPTION_WARNING: "WAITING_FOR_ACTIVE_PRESCRIPTION_WARNING",
    FOR_BIRTHDATE_INPUT_MESSAGE: "WAITING_FOR_BIRTHDATE_INPUT_MESSAGE",
    FOR_CONFIRMATION_OF_PRESCRIPTION_RENEWAL:
      "WAITING_FOR_CONFIRMATION_OF_PRESCRIPTION_RENEWAL",
    FOR_CONFIRMATION: "WAITING_FOR_CONFIRMATION",
    FOR_EPS_SERVICES_LIST: "WAITING_FOR_EPS_SERVICES_LIST",
    FOR_ID_NUMBER_INPUT_MESSAGE: "WAITING_FOR_ID_NUMBER_INPUT_MESSAGE",
    FOR_ID_TYPE_LIST: "WAITING_FOR_ID_TYPE_LIST",
    FOR_MAIN_MENU: "WAITING_FOR_MAIN_MENU",
    FOR_PRESCRIPTION_RENEWAL_SUCCESS:
      "WAITING_FOR_PRESCRIPTION_RENEWAL_SUCCESS",
    FOR_PROCEDURES_MESSAGE: "WAITING_FOR_PROCEDURES_MESSAGE",
    FOR_PROCS_AND_MEDS_MENU: "WAITING_FOR_PROCS_AND_MEDS_MENU",
  },
  COMPLETED: "COMPLETED",
} as const;

// Respuestas predefinidas del bot al menú de procedimientos
export const PROCEDURE_OPTIONS = {
  RENEW_MEDS: "3", // Renovación mensual formula de medicamentos
} as const;

// Posibles eventos
export const EVENTS = {
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  WS_CLIENT_READY: "WS_CLIENT_READY",
} as const;

export const ID_TYPES = {
  CEDULA_CIUDADANIA: "Cédula de ciudadanía",
  CEDULA_EXTRANJERIA: "Cédula de extranjería",
  TARJETA_IDENTIDAD: "Tarjeta de identidad",
  NIT: "NIT",
  PASAPORTE: "Pasaporte",
  PASAPORTE_DIPLOMATICO: "Pasaporte diplomático",
  REGISTRO_CIVIL: "Registro civil",
  TARJETA_EXTRANJERIA: "Tarjeta de Extranjería",
  NUIP: "NUIP",
  OTHER: "Otro",
} as const;

export const ID_TYPES_ARRAY = Object.values(ID_TYPES);
